### ISSUE TITLE
Reorganize the GUI of `PersonCard`

### ISSUE THREAD

**Issue by weiseng18** [AY2425S1-CS2103T-F12-1/tp#119]

**Comment by lithops-zty** [comment]
Rough sketch:
![image](https://github.com/user-attachments/assets/e6fa6168-dcc9-42d0-9d41-3f8cecb0d152)

Some design I propose to include:
1. Put an icon in the right side of the module tag to indicate the role (i.e. one icon each for Professor, TA and Student). The icons I chose above may not be the most intuitive and we can find better options online. I recommend [Alibaba Vector Icon Library](https://www.iconfont.cn/) which offers plenty of free icons.
2. Use different colors for each role as well, so that the user can know the role instantly after they get used to our color scheme.

**Comment by weiseng18** [comment]
done in #133
