### ISSUE TITLE
Enhance edit command result message to give user clear ideas when some changes are not made

### ISSUE THREAD

**Issue by MAOXIONGKAI** [AY2425S1-CS2103T-F12-1/tp#142]
1. For long edit command in which only some of the inputs are accepted and the rest does not work(same data, conflicting modules roles etc), user may find it hard to determine what are the things they input wrongly/not accepted. Sometimes they may need to compare their inputs with changes made to find out the inputs that are not accepted. Hence, this would introduce inefficiency and may be considered as `FeatureFlaw`
2. Also, if a long edit command happens to make no changes at all. May be it would be better to specify the reasons why no changes made. Like giving a list Phone number is the same., Module already existing in the Role etc
3. Current idea is that can simply track the changes that fail in another StringBuilder and input that after the successful changes(if any),so that they can serve as useful error message in case user needs them.

**Comment by lithops-zty** [comment]
We have agreed to, instead of this approach, directly raise an error whenever there is some module-role pair given that will cause problems. The user will have to correct all the pairs before the command makes actual changes to the data.
Since an error will be displayed even when only some given pairs are problematic, this issue is no longer relevant.
