### ISSUE TITLE
Implement undo and redo

### ISSUE THREAD

**Issue by lithops-zty** [AY2425S1-CS2103T-F12-1/tp#158]
UI:
- add a panel on the right showing history commands executed

Backend:
- follow proposed approach on DG

**Comment by weiseng18** [comment]
# Proposed idea:

User should type in `undo` and press `<Enter>` to execute `UndoCommand`. Assumption for the first 2 section is that we only implement undo. The 3rd section explains how we implement redo, after implementing undo

### UI 

- UI resembles a stack of commands that modified the list. (add, edit, clear, delete).
- When a new modify command is run, add this to the top of the stack.
- When `undo` is run, we can pop the top of the stack. (Assumption here is that we are only planning to implement undo.)

### Backend:

This is not explicitly discussed yet, but I think we should go with option 1 since it is a universal method which is easier to implement.

- Update the current list with `stateList[stateList.length - 2]`
- Pop the last element in the list (Assumption here is that we are only planning to implement undo.)

![image](https://github.com/user-attachments/assets/8a8aa55c-8461-4b08-a351-cae53a22f4ad)

### Future redo support:

- Now, we cannot simply pop the last element from the `stateList` (in backend), and cannot simply pop the "stack" (in the frontend).
- In the backend,
  - we have to store an index to refer to where we are in the `stateList`, then decrement when undo and increment when redo.
  - if we run a modifying command, and we are not at the last element of the `stateList`, then we will delete everything from `index+1` all the way to the end of the `stateList`, before we add the new state that this modifying command produces
- In the frontend,
  - we now use a pointer to indicate where we are in the command history
  - move the pointer down if we undo, move the pointer up if we redo
  - IMPORTANT: this should be possible, but we should check if JavaFX allows us to modify the scroll position of the GUI. This is because if we keep running `undo`, we might go back too far in history and the pointer goes beyond the viewport of the command history window

**Comment by weiseng18** [comment]
Other points of discussion:

1. Are we ok that the "command history" on the right only shows commands that modify the list?
2. This approach means that undo/redo will refer to only the modifying commands as the history timeline.
3. How to display undo

**Comment by MAOXIONGKAI** [comment]
@weiseng18 
Thanks for the detailed description on this part! I think implementing both undo/redo should be feasible because such implemented as been given in [AB4 Developer Guide](https://se-education.org/addressbook-level4/DeveloperGuide.html#undo-redo-feature). If you haven't read through this, I think maybe we can discuss on the feasibility of fully adapting this approach, or any adjustments to be made to match our own product requirements. Regard rest of the things, since I am the one doing undo/redo feature, I will seek advice from @lithops-zty as well, thank you
